#ifndef SAVEBOX_BOARD_H
#define SAVEBOX_BOARD_H

#include "ESP_BSP/bsp_platform.h"
#include "esp_adc/adc_oneshot.h"

#define SAVEBOX_UNUSED_PORT ((GPIO_TypeDef *)0)

// ...existing code...
/*
 * 适用于当前 ESP32-S3-CAM + 自定义传感器扩展板的推荐默认配置：
 * - 保持相机、Wi‑Fi/MQTT、DHT11、MQ2 和 SW180 启用
 * - 在 RC522 的引脚重新映射以避开当前冲突布线之前，保持其 SPI 总线禁用
 * - 避免在 BSP 阶段过早初始化 GPIO36/GPIO37；这些引脚仅在其任务/模块稍后访问时才稳定
 */
// ...existing code...

#ifndef SAVEBOX_BUZZER_GPIO
#define SAVEBOX_BUZZER_GPIO GPIO_NUM_36
#endif

#ifndef SAVEBOX_CAMERA_ENABLE
#define SAVEBOX_CAMERA_ENABLE 1
#endif

#ifndef SAVEBOX_CAMERA_ONLY_ISOLATION
#define SAVEBOX_CAMERA_ONLY_ISOLATION 0
#endif

#ifndef SAVEBOX_ENABLE_TASK_CAMERA
#define SAVEBOX_ENABLE_TASK_CAMERA 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_BUZZER
#define SAVEBOX_ENABLE_TASK_BUZZER 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_SERVO
#define SAVEBOX_ENABLE_TASK_SERVO 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_UART
#define SAVEBOX_ENABLE_TASK_UART 0
#endif

#ifndef SAVEBOX_ENABLE_TASK_DHT11
#define SAVEBOX_ENABLE_TASK_DHT11 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_RC522
#define SAVEBOX_ENABLE_TASK_RC522 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_RC522_DEFERRED_STARTUP
#define SAVEBOX_ENABLE_TASK_RC522_DEFERRED_STARTUP 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_MQ2
#define SAVEBOX_ENABLE_TASK_MQ2 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_SW180
#define SAVEBOX_ENABLE_TASK_SW180 1
#endif

#ifndef SAVEBOX_ENABLE_TASK_OLED
#define SAVEBOX_ENABLE_TASK_OLED 1
#endif

#ifndef SAVEBOX_ENABLE_APP_CAMERA
#define SAVEBOX_ENABLE_APP_CAMERA 1
#endif

#ifndef SAVEBOX_ENABLE_APP_SW180
#define SAVEBOX_ENABLE_APP_SW180 0
#endif

#ifndef SAVEBOX_ENABLE_APP_RC522
#define SAVEBOX_ENABLE_APP_RC522 0
#endif

#ifndef SAVEBOX_ENABLE_APP_MQ2
#define SAVEBOX_ENABLE_APP_MQ2 0
#endif

#ifndef SAVEBOX_ENABLE_APP_SERVO
#define SAVEBOX_ENABLE_APP_SERVO 0
#endif

#ifndef SAVEBOX_ENABLE_BSP_PLATFORM
#define SAVEBOX_ENABLE_BSP_PLATFORM 1
#endif

#ifndef SAVEBOX_ENABLE_BSP_UART_DRIVER
#define SAVEBOX_ENABLE_BSP_UART_DRIVER 0
#endif

#ifndef SAVEBOX_ENABLE_BSP_RC522_SPI_BUS
#define SAVEBOX_ENABLE_BSP_RC522_SPI_BUS 1
#endif

#ifndef SAVEBOX_ENABLE_BSP_BUZZER_GPIO_INIT
#define SAVEBOX_ENABLE_BSP_BUZZER_GPIO_INIT 0
#endif

#ifndef SAVEBOX_ENABLE_BSP_DHT11_GPIO_INIT
#define SAVEBOX_ENABLE_BSP_DHT11_GPIO_INIT 1
#endif

#ifndef SAVEBOX_ENABLE_BSP_SW180_GPIO_INIT
#define SAVEBOX_ENABLE_BSP_SW180_GPIO_INIT 0
#endif

#ifndef SAVEBOX_ENABLE_BSP_RC522_GPIO_INIT
#define SAVEBOX_ENABLE_BSP_RC522_GPIO_INIT 1
#endif

#ifndef SAVEBOX_CAMERA_PWDN_GPIO
#define SAVEBOX_CAMERA_PWDN_GPIO GPIO_NUM_NC
#endif

#ifndef SAVEBOX_CAMERA_RESET_GPIO
#define SAVEBOX_CAMERA_RESET_GPIO GPIO_NUM_3
#endif

#ifndef SAVEBOX_CAMERA_XCLK_GPIO
#define SAVEBOX_CAMERA_XCLK_GPIO GPIO_NUM_15
#endif

#ifndef SAVEBOX_CAMERA_SIOD_GPIO
#define SAVEBOX_CAMERA_SIOD_GPIO GPIO_NUM_4
#endif

#ifndef SAVEBOX_CAMERA_SIOC_GPIO
#define SAVEBOX_CAMERA_SIOC_GPIO GPIO_NUM_5
#endif

#ifndef SAVEBOX_CAMERA_VSYNC_GPIO
#define SAVEBOX_CAMERA_VSYNC_GPIO GPIO_NUM_6
#endif

#ifndef SAVEBOX_CAMERA_HREF_GPIO
#define SAVEBOX_CAMERA_HREF_GPIO GPIO_NUM_7
#endif

#ifndef SAVEBOX_CAMERA_PCLK_GPIO
#define SAVEBOX_CAMERA_PCLK_GPIO GPIO_NUM_13
#endif

#ifndef SAVEBOX_CAMERA_D0_GPIO
#define SAVEBOX_CAMERA_D0_GPIO GPIO_NUM_11
#endif

#ifndef SAVEBOX_CAMERA_D1_GPIO
#define SAVEBOX_CAMERA_D1_GPIO GPIO_NUM_9
#endif

#ifndef SAVEBOX_CAMERA_D2_GPIO
#define SAVEBOX_CAMERA_D2_GPIO GPIO_NUM_8
#endif

#ifndef SAVEBOX_CAMERA_D3_GPIO
#define SAVEBOX_CAMERA_D3_GPIO GPIO_NUM_10
#endif

#ifndef SAVEBOX_CAMERA_D4_GPIO
#define SAVEBOX_CAMERA_D4_GPIO GPIO_NUM_12
#endif

#ifndef SAVEBOX_CAMERA_D5_GPIO
#define SAVEBOX_CAMERA_D5_GPIO GPIO_NUM_18
#endif

#ifndef SAVEBOX_CAMERA_D6_GPIO
#define SAVEBOX_CAMERA_D6_GPIO GPIO_NUM_17
#endif

#ifndef SAVEBOX_CAMERA_D7_GPIO
#define SAVEBOX_CAMERA_D7_GPIO GPIO_NUM_16
#endif

#ifndef SAVEBOX_CAMERA_XCLK_FREQ_HZ
#define SAVEBOX_CAMERA_XCLK_FREQ_HZ 20000000U
#endif

#ifndef SAVEBOX_DHT11_GPIO
#define SAVEBOX_DHT11_GPIO GPIO_NUM_2
#endif

#ifndef SAVEBOX_SERVO_GPIO
#define SAVEBOX_SERVO_GPIO GPIO_NUM_35
#endif

#ifndef SAVEBOX_SW180_DO_GPIO
#define SAVEBOX_SW180_DO_GPIO GPIO_NUM_37
#endif

#ifndef SAVEBOX_SW180_TRIGGER_LEVEL
#define SAVEBOX_SW180_TRIGGER_LEVEL GPIO_PIN_RESET
#endif

#ifndef SAVEBOX_MQ2_ADC_GPIO
#define SAVEBOX_MQ2_ADC_GPIO GPIO_NUM_1
#endif

#ifndef SAVEBOX_MQ2_ADC_UNIT
#define SAVEBOX_MQ2_ADC_UNIT ADC_UNIT_1
#endif

#ifndef SAVEBOX_MQ2_ADC_CHANNEL
#define SAVEBOX_MQ2_ADC_CHANNEL ADC_CHANNEL_0
#endif

#ifndef SAVEBOX_MQ2_ADC_ATTEN
#define SAVEBOX_MQ2_ADC_ATTEN ADC_ATTEN_DB_12
#endif

#ifndef SAVEBOX_MQ2_WARMUP_MS
#define SAVEBOX_MQ2_WARMUP_MS 60000U
#endif

#ifndef SAVEBOX_MQ2_DELTA_WINDOW_MS
#define SAVEBOX_MQ2_DELTA_WINDOW_MS 2000U
#endif

#ifndef SAVEBOX_MQ2_DELTA_ALARM_THRESHOLD_RAW
#define SAVEBOX_MQ2_DELTA_ALARM_THRESHOLD_RAW 300
#endif

#ifndef SAVEBOX_RC522_MOSI_GPIO
#define SAVEBOX_RC522_MOSI_GPIO GPIO_NUM_42
#endif

#ifndef SAVEBOX_RC522_MISO_GPIO
#define SAVEBOX_RC522_MISO_GPIO GPIO_NUM_40
#endif

#ifndef SAVEBOX_RC522_SCK_GPIO
#define SAVEBOX_RC522_SCK_GPIO GPIO_NUM_14
#endif

#ifndef SAVEBOX_RC522_NSS_GPIO
#define SAVEBOX_RC522_NSS_GPIO GPIO_NUM_39
#endif

#ifndef SAVEBOX_RC522_RST_GPIO
#define SAVEBOX_RC522_RST_GPIO GPIO_NUM_38
#endif

#ifndef SAVEBOX_RC522_SPI_HOST
#define SAVEBOX_RC522_SPI_HOST SPI2_HOST
#endif

#ifndef SAVEBOX_RC522_SPI_CLOCK_HZ
#define SAVEBOX_RC522_SPI_CLOCK_HZ (1000 * 1000)
#endif

#ifndef SAVEBOX_RC522_SPI_DMA_CHAN
#define SAVEBOX_RC522_SPI_DMA_CHAN SPI_DMA_DISABLED
#endif

#ifndef SAVEBOX_SERVO_PWM_FREQ_HZ
#define SAVEBOX_SERVO_PWM_FREQ_HZ 50U
#endif

#ifndef SAVEBOX_UART_PORT
#define SAVEBOX_UART_PORT UART_NUM_0
#endif

#ifndef SAVEBOX_OLED_SCL_GPIO
#define SAVEBOX_OLED_SCL_GPIO GPIO_NUM_21
#endif

#ifndef SAVEBOX_OLED_SDA_GPIO
#define SAVEBOX_OLED_SDA_GPIO GPIO_NUM_47
#endif

#ifndef SAVEBOX_OLED_RESET_GPIO
#define SAVEBOX_OLED_RESET_GPIO GPIO_NUM_NC
#endif

#ifndef SAVEBOX_OLED_AUTO_INIT
#define SAVEBOX_OLED_AUTO_INIT 0
#endif

#ifndef SAVEBOX_UART_TX_GPIO
#define SAVEBOX_UART_TX_GPIO UART_PIN_NO_CHANGE
#endif

#ifndef SAVEBOX_UART_RX_GPIO
#define SAVEBOX_UART_RX_GPIO UART_PIN_NO_CHANGE
#endif

#ifndef SAVEBOX_UART_BAUD_RATE
#define SAVEBOX_UART_BAUD_RATE 115200U
#endif

#ifndef SAVEBOX_RC522_CARD_COOLDOWN_MS
#define SAVEBOX_RC522_CARD_COOLDOWN_MS 2000U
#endif

#ifndef SAVEBOX_RC522_WHITE_UID0
#define SAVEBOX_RC522_WHITE_UID0 0x64
#endif

#ifndef SAVEBOX_RC522_WHITE_UID1
#define SAVEBOX_RC522_WHITE_UID1 0x6E
#endif

#ifndef SAVEBOX_RC522_WHITE_UID2
#define SAVEBOX_RC522_WHITE_UID2 0x1C
#endif

#ifndef SAVEBOX_RC522_WHITE_UID3
#define SAVEBOX_RC522_WHITE_UID3 0x06
#endif

#define Buzzer_GPIO_Port SAVEBOX_UNUSED_PORT
#define Buzzer_Pin SAVEBOX_BUZZER_GPIO

#define DHT11_DATA_GPIO_Port SAVEBOX_UNUSED_PORT
#define DHT11_DATA_Pin SAVEBOX_DHT11_GPIO

#define SW180_DO_GPIO_Port SAVEBOX_UNUSED_PORT
#define SW180_DO_Pin SAVEBOX_SW180_DO_GPIO

#define RC522_MOSI_GPIO_Port SAVEBOX_UNUSED_PORT
#define RC522_MOSI_Pin SAVEBOX_RC522_MOSI_GPIO
#define RC522_MISO_GPIO_Port SAVEBOX_UNUSED_PORT
#define RC522_MISO_Pin SAVEBOX_RC522_MISO_GPIO
#define RC522_SCK_GPIO_Port SAVEBOX_UNUSED_PORT
#define RC522_SCK_Pin SAVEBOX_RC522_SCK_GPIO
#define RC522_NSS_GPIO_Port SAVEBOX_UNUSED_PORT
#define RC522_NSS_Pin SAVEBOX_RC522_NSS_GPIO
#define RC522_RST_GPIO_Port SAVEBOX_UNUSED_PORT
#define RC522_RST_Pin SAVEBOX_RC522_RST_GPIO

#endif
