idf_component_register(
    SRCS
        "main.c"
        "../MQTT/savebox_mqtt.c"
        "../MQTT/savebox_http_upload.c"
        "../ESP_APP/app_Buzzer.c"
        "../ESP_APP/app_camera.c"
        "../ESP_APP/app_DHT11.c"
        "../ESP_APP/app_list.c"
        "../ESP_APP/app_mq2.c"
        "../ESP_APP/app_rc522.c"
        "../ESP_APP/app_servo.c"
        "../ESP_APP/app_sw180.c"
        "../ESP_BSP/app_oled.c"
        "../ESP_BSP/bsp_adc.c"
        "../ESP_BSP/bsp_delay.c"
        "../ESP_BSP/bsp_gpio.c"
        "../ESP_BSP/bsp_list.c"
        "../ESP_BSP/bsp_platform.c"
        "../ESP_BSP/bsp_timer.c"
        "../ESP_BSP/bsp_uart.c"
        "../ESP_BSP/OLED_font.c"
        "../task/task_buzzer.c"
        "../task/task_camera.c"
        "../task/task_dht11.c"
        "../task/task_list.c"
        "../task/task_mq2.c"
        "../task/task_oled.c"
        "../task/task_rc522.c"
        "../task/task_servo.c"
        "../task/task_state.c"
        "../task/task_sw180.c"
        "../task/task_uart.c"
    INCLUDE_DIRS
        "."
        ".."
        "../MQTT"
        "../compat"
        "../ESP_APP"
        "../ESP_BSP"
        "../task"
    REQUIRES
        esp_event
        esp_http_client
        esp_netif
        esp_psram
        esp_adc
        esp_driver_gpio
        esp_driver_ledc
        esp_driver_spi
        esp_driver_uart
        esp_timer
        esp_wifi
        json
        mbedtls
        mqtt
        nvs_flash
        esp32-camera
        spi_flash
)
