#ifndef SAVEBOX_MQTT_CONFIG_H
#define SAVEBOX_MQTT_CONFIG_H

#define SAVEBOX_WIFI_SSID "Xiaomi 15"
#define SAVEBOX_WIFI_PASSWORD "hjj05826"

#define SAVEBOX_MQTT_BROKER_URI "mqtts://720e1b4a1a.st1.iotda-device.cn-north-4.myhuaweicloud.com:8883"
#define SAVEBOX_MQTT_USERNAME "6a0337a0cbb0cf6bb95a288b_ESP32_savebox"
#define SAVEBOX_MQTT_PASSWORD "c386ce66dd4dce344f5726219b04ab1644289ae32406a39806a54d2c68086a6e"
#define SAVEBOX_MQTT_CLIENT_ID "6a0337a0cbb0cf6bb95a288b_ESP32_savebox_0_1_2026051214"
#define SAVEBOX_MQTT_DEVICE_ID "6a0337a0cbb0cf6bb95a288b_ESP32_savebox"

#define SAVEBOX_MQTT_SERVICE_ID "savebox_state"
#define SAVEBOX_MQTT_COMMAND_LOCK "lock"
#define SAVEBOX_MQTT_COMMAND_LOCK_PARAM "setLock"
#define SAVEBOX_MQTT_COMMAND_SYNC_STATUS "syncStatus"
#define SAVEBOX_MQTT_COMMAND_BEEP "beep"
#define SAVEBOX_MQTT_COMMAND_BEEP_PARAM "durationMs"
#define SAVEBOX_MQTT_COMMAND_RESPONSE_NAME "COMMAND_RESPONSE"

#define SAVEBOX_MQTT_PROPERTIES_REPORT_TOPIC "$oc/devices/" SAVEBOX_MQTT_DEVICE_ID "/sys/properties/report"
#define SAVEBOX_MQTT_MESSAGES_UP_TOPIC "$oc/devices/" SAVEBOX_MQTT_DEVICE_ID "/sys/messages/up"
#define SAVEBOX_MQTT_COMMAND_SUB_TOPIC "$oc/devices/" SAVEBOX_MQTT_DEVICE_ID "/sys/commands/#"
#define SAVEBOX_MQTT_COMMAND_RESPONSE_TOPIC_PREFIX "$oc/devices/" SAVEBOX_MQTT_DEVICE_ID "/sys/commands/response/request_id="
#define SAVEBOX_MQTT_COMMAND_REQUEST_ID_MARKER "request_id="

#define SAVEBOX_MQTT_PUBLISH_PERIOD_MS 5000U
#define SAVEBOX_MQTT_WIFI_MAXIMUM_RETRY 10U
#define SAVEBOX_MQTT_KEEPALIVE_SECONDS 120U
#define SAVEBOX_MQTT_DEFAULT_BEEP_MS 1000U

#define SAVEBOX_HTTP_BASE_URL "http://192.168.31.120:3000"
#define SAVEBOX_HTTP_LATEST_FRAME_URL SAVEBOX_HTTP_BASE_URL "/api/camera/latest-frame"
#define SAVEBOX_HTTP_ALARM_FRAME_URL SAVEBOX_HTTP_BASE_URL "/api/camera/alarm-frame"
#define SAVEBOX_HTTP_STATUS_URL SAVEBOX_HTTP_BASE_URL "/api/device/status"
#define SAVEBOX_HTTP_LATEST_FRAME_PERIOD_MS 2000U
#define SAVEBOX_HTTP_STATUS_PERIOD_MS 5000U
#define SAVEBOX_HTTP_REQUEST_TIMEOUT_MS 5000U

#endif
